# Discovery Server Dashboard uses FreeMarker.  Don't want Thymeleaf templates
spring:
  thymeleaf:
    enabled: false     # Disable Thymeleaf
    
server:
  port: ${PORT:1111}  #HTTP (Tomcat) port
security:
  basic:
    enabled: true
  user:
    name: ${EUREKA_USER_NAME:admin}
    password: ${EUREKA_USER_PASSWORD:password}
    role: USER,ADMIN
      #password: ${eureka.password}
    
# Configure this Discovery Server
eureka:
  instance:
    hostname: localhost
  client:
    registerWithEureka: false
    fetchRegistry: false
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/